name: pr-broker

on:
  pull_request_target:
  pull_request_review:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run-pr-broker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: local pr-broker
        uses: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
